# Publications and Authorship

Science is a team sport. We advance our careers through collaboration and intellectual contribution. Papers authored within the lab should recognize serious substantive intellectual contribution through authorship. When in doubt, discuss it with an eye towards generosity - particularly to more junior members. An undergraduate doing both intellectual and manual work on a project will benefit from inclusion in ways that more senior colleagues can easily forget. 

Further, we encourage all members, whenever engaging collaboration inside or outside of the lab, to discuss authorship *first* before doing the work in order to make sure contributions are recognized to alleviate any future doubt. This is particularly important if this is a new collaborative arrangement. Prof. Byrnes will work his hardest at contributing to all work going on in the lab and sign on as senior (i.e., last) author - but only if it feels warranted by those leading the work.

As a lab, we support open access to all research. We recognize, at the same time, that the incentives of journal publishing do not always make open access journals possible. This placement of professional advancement within the system versus the ethics of publication is a difficult path to navigate. As such, we try and put all manuscripts up as preprints at either [bioRxiv](https://www.biorxiv.org/), [arXiv](https://arxiv.org/), or [ecoevoRxiv](https://ecoevorxiv.org/) along with revisions to ensure accessibility and early access by colleagues.
