# CELP Lab Code of Conduct


## Overview
Here in the CELP Lab, we are dedicated to understanding the forces that shape life in the ocean and what they mean for the ever changing world. To do this, we acknowledge our role in shaping a positive, vibrant, and inclusive environment where we can spread our love of knowledge and of the sea. With this code of conduct, we seek to lay out policies and norms that will enable those goals.

## The Quick Version

In our lab, we are dedicated to creating a safe, welcoming, and healthy environment to nurture the best research and researchers to move science forward. This includes providing a harrassment-free space and welcome anyone regardless of the myriad facets of human diversity. We are here for the work and for our love of science and the sea. Discriminatory behavior, dehumanizing and objectifying language or imagery in any context, or lack of respect of each other - particularly with respect to the aforementioned categories, has no place in this lab. Nor in science, really. We want to make the culture of science better, starting at home.

## Inclusivity and Diversity

Science has for too long been the domain of white able-bodied cis-gendered men of means. This has ramifications for the ideas and perspectives that can be considered within science and, moreover, means that science does not reflect society. How many contributions and stunning discoveries have been lost?  

In our lab, we welcome and encourage the participation of anyone regardless of race, gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, religious beliefs, socioeconomic background, nationality, or the many other categories not explicitly mentioned here. We recognize that many members of the lab or those who wish to be part of the lab come from backgrounds with significant challenges to participate in science. Our job is to listen to them, to believe them, to be allies in ways that are helpful, to help each other overcome barriers on their path to being great scientists, rather than putting more in front of them.

Discrimination against any of these will not be tolerated. Interactions within the lab, while encouraged to be friendly and informal, must conform to best professional behavior. Conversations of a sexual nature, unwanted comments regarding race or religious background, discussion of physical bodies, sending graphic imagery, persistent harassment, and other unprofessional interactions are not appropriate and are likewise not tolerated within the lab.

It is the responsibility of all members of the lab to maintain a safe, mentally healthy, productive, and professional environment.

We do recognize recognize mistakes happen. Unintentional microagressions - particularly those learned over time in the past as something perceived as harmless - will happen, even with no malice or bad intentions. We are all working on ourselves, and we will all say and do things we do not mean. In that case, it is incumbent upon us to listen, to not immediately engage in defensive deflection, to learn from the mistake, to make a repair, and do the work to do better.

## Respect for Mental Health

Working in science can be difficult for one's mental health. We are constantly at the cutting edge, and failure is constant - both in terms of results of our work and rejection in the form of grant proposals and papers. In the modern university, we are also asked to wear many hats, often at the same time. Mental health has long carried a stigma in academia, and it's time to move past that and acknowledge the reality.

In the CELP Lab, we know that your mental health is crucial for being a great scientist. You should never feel obligated to push yourself to be unhealthy. Take breaks. Go on vacation. Have a hobby. Read a book - the trashier the better! Cook elaborate meals! Send us the recipes! Do the things you need to do to have a healthy balanced life. If you feel this is not possible, have a discussion with Prof. Byrnes and other members of the lab.

We all work to be healthy and happy. Whether it's retooling your expectations of yourself, tackling your [imposter syndrome](https://en.wikipedia.org/wiki/Impostor_syndrome) (we have all been there), or, heck, considering the importance of therapy (even Prof. Byrnes engages in it!), let's talk about it. It's the most important thing.

## Working Environment

The first goal of everyone in the lab is the success of all of their labmates! We want to succeed, advance our careers, push science forward, and enjoy doing it. As such, all interactions with each other - from daily conversation to feedback to working together in the field - should take place from a place of support and our mutual success. Listening, empathy, mindfulness, and mutual respect are cornerstones of the environment we want to create. We want to have a positive environment.

Harassment of any kind - including but not limited to discrimination, unwanted sexual advances, unwanted sexual comments, undesired attention, and use of power to take advantage of others are not tolerated. Our lab is not a place for put downs or come ons.

We are also all human. If you have erred, listen to the feedback on your actions - be it from the person involved, from Prof. Byrnes, or others who become involved in this discussion. Listen. Learn. Make meaningful restitution. And know that forgiveness may not be granted to you in the way you want. We can only grow.

Above all, we strive to make the working environment to be intellectually stimulating, enjoyable, and allow for everyone involved to grow and become better people and scientists than when they first arrived.

## Social Media

Social Media is a way to participate in the online conversation. It is a springboard to being a public intellectual which, frankly as public university scientists, we are! It also provides ample opportunities for communicating with colleagues that you might never otherwise encounter, and allow for scientific cross-pollination that can lead to great places! That said, social media is a place where you are constantly presenting a crafted version of who you are. It can also be a tricky sphere to navigate, rife with misunderstanding and others who are not plain dealers.

In the CELP Lab, we encourage any and all members to participate in social media on whatever platform is most comfortable - or none at all! Your account is your own, and we would not seek to have it any other way. That said, while you are a member of this lab, we ask that you be mindful that your words, pictures, and actions can reflect back on your entire lab group. We ask for mindfulness in your use of social media. In particular, hate speech, threats, or harassment of any sort runs counter to our values as a lab group.


## Enforcement

Below, we enumerate our values as a lab. But, a statement of values without Enforcement is meaningless. In the case of a violation of any element of our code of conduct, please discuss it with Prof. Byrnes. He will talk to the responsible party - both to attempt to rectify the immediate situation but also to start a dialogue around understanding why this is an important tenant of being a scientist in the modern world. If the problem persists, this could lead to a more serious discussion of the member's role within the lab. At any time, if warranted, Prof. Byrnes is happy to bring in the chair, GPD, or other relevant element of the University administration. For appropriate issues, Prof. Byrnes is happy to consult with [UMB Office of Civil Rights and Title IX](https://www.umb.edu/crtix) or the [Office of Diversity, Equity, and Inclusion](https://www.umb.edu/odei). If, for whatever reason, you feel uncomfortable  discussing a problem with Prof. Byrnes, you are encouraged to approach these resources.