# Data Management

# Open Data Policy

Open data is the key to scientific reproducibility and synthesis for the advancement of knowledge. All data collected by CELP Lab members must be open at time of publication of manuscripts or within two years of completion of your time in this lab. We suggest using The [Environmental Data Initiative](https://edirepository.org) (preferred), The [Knowledge Network for Biocomplexity](https://knb.ecoinformatics.org/), [Temperate Reefbase](https://temperatereefbase.imas.utas.edu.au/static/landing.html), [Data Dryad](https://datadryad.org/stash), or other appropriate LTER or other repository for your data, as there it must not only meet their quality standards by also have the appropriate meta-data for re-use. All publications must include the DOI and reference to the data. All data, when released, must meet [FAIR](https://www.go-fair.org/fair-principles/) (Findability, Accessibility, Interoperability, and Reuse) principles.

Similarly, all code must be made public at time of publication so that your work is fully reproducible. We suggest using [GitHub](http://github.com) and, at time of publication, making a formal code release via [Zenodo](https://zenodo.org) which seamlessly links to GitHub so that you can get a DOI that can be referenced in the manuscript in addition to including it as a code supplement.

When possible, develop your data and code in the open! Again, we highly recommend [GitHub](http://github.com).
